import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { LessonPlanResponse } from "../types";

const formatFileName = (title: string) => {
    return title.replace(/[^a-z0-9]/gi, '_').toLowerCase().substring(0, 30);
}

export const downloadLessonPlanPDF = (plan: LessonPlanResponse) => {
  const doc = new jsPDF();
  const margin = 14;
  
  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  doc.text(plan.title, margin, 20);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by VietPlan AI`, margin, 26);

  let yPos = 35;

  // Objectives
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text("Objectives", margin, yPos);
  yPos += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  plan.objectives.forEach((obj) => {
    const lines = doc.splitTextToSize(`• ${obj}`, 180);
    doc.text(lines, margin, yPos);
    yPos += (lines.length * 5) + 2;
  });
  yPos += 5;

  // Warm Up
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text("Warm Up", margin, yPos);
  yPos += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  const warmUpLines = doc.splitTextToSize(plan.warmUp, 180);
  doc.text(warmUpLines, margin, yPos);
  yPos += (warmUpLines.length * 5) + 10;

  // Schedule Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text("Lesson Schedule", margin, yPos);
  yPos += 5;

  const tableBody = plan.schedule.map(item => [
    item.time,
    item.interaction,
    item.activityName,
    item.procedure
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [['Time', 'Interaction', 'Activity', 'Procedure']],
    body: tableBody,
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 10, cellPadding: 3, overflow: 'linebreak' },
    columnStyles: {
      0: { cellWidth: 20, fontStyle: 'bold' },
      1: { cellWidth: 25 },
      2: { cellWidth: 40, fontStyle: 'bold', textColor: [60, 60, 60] },
      3: { cellWidth: 'auto' }
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Games
  if (plan.games.length > 0) {
      if (yPos > 250) { doc.addPage(); yPos = 20; }
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(40, 40, 40);
      doc.text("Games & Activities", margin, yPos);
      yPos += 10;

      plan.games.forEach((game, index) => {
          if (yPos > 230) { doc.addPage(); yPos = 20; }

          doc.setFont("helvetica", "bold");
          doc.setFontSize(12);
          doc.setTextColor(0, 0, 0);
          doc.text(`${index + 1}. ${game.name}`, margin, yPos);
          yPos += 6;

          doc.setFont("helvetica", "italic");
          doc.setFontSize(10);
          doc.setTextColor(100, 100, 100);
          doc.text(`Materials: ${game.materialsNeeded}`, margin, yPos);
          yPos += 6;

          doc.setFont("helvetica", "normal");
          doc.setFontSize(11);
          doc.setTextColor(60, 60, 60);
          const instructions = doc.splitTextToSize(game.instructions, 180);
          doc.text(instructions, margin, yPos);
          yPos += (instructions.length * 5) + 8;
      });
  }

  // Teacher Notes
  if (plan.teacherNotes) {
    if (yPos > 240) { doc.addPage(); yPos = 20; }
    
    yPos += 5;
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPos, 210 - margin, yPos);
    yPos += 10;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(40, 40, 40);
    doc.text("Teacher's Notes", margin, yPos);
    yPos += 7;

    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    const notes = doc.splitTextToSize(plan.teacherNotes, 180);
    doc.text(notes, margin, yPos);
  }

  doc.save(`${formatFileName(plan.title)}_plan.pdf`);
};

export const downloadMaterialsPDF = (plan: LessonPlanResponse) => {
  const doc = new jsPDF();
  const margin = 20;
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Lesson Materials", margin, 20);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Topic: ${plan.title}`, margin, 30);

  doc.setDrawColor(0);
  doc.line(margin, 35, 190, 35);

  const lines = doc.splitTextToSize(plan.worksheetContent, 170);
  doc.text(lines, margin, 45);
  
  doc.save(`${formatFileName(plan.title)}_materials.pdf`);
};

export const downloadHomeworkPDF = (plan: LessonPlanResponse) => {
  const doc = new jsPDF();
  const margin = 20;
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Homework Assignment", margin, 20);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Topic: ${plan.title}`, margin, 30);

  doc.setDrawColor(0);
  doc.line(margin, 35, 190, 35);

  const lines = doc.splitTextToSize(plan.homework, 170);
  doc.text(lines, margin, 45);
  
  doc.save(`${formatFileName(plan.title)}_homework.pdf`);
};